// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeZgAwXhtxzTsdevqZVfKQCJWX23pd6g',
    appId: '1:937529806462:web:2ec78dd2e405ac4269922f',
    messagingSenderId: '937529806462',
    projectId: 'chat-app-cce2e',
    authDomain: 'chat-app-cce2e.firebaseapp.com',
    storageBucket: 'chat-app-cce2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHNTIyuDUS-q1aahg71mVNc_kBHhuQYs',
    appId: '1:937529806462:android:345e53b304b57f2b69922f',
    messagingSenderId: '937529806462',
    projectId: 'chat-app-cce2e',
    storageBucket: 'chat-app-cce2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb6I77uisVYCBwyeMVl6d_LEpJ8gVsg80',
    appId: '1:937529806462:ios:9f2aa0389836b68069922f',
    messagingSenderId: '937529806462',
    projectId: 'chat-app-cce2e',
    storageBucket: 'chat-app-cce2e.appspot.com',
    iosClientId: '937529806462-v5fdikl7c23fcn3e0dm3ti80c9n69g1u.apps.googleusercontent.com',
    iosBundleId: 'carewellapp',
  );
}
