// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWOFkpNziTsGYnFB4TiVxJeR7hvCoQR4k',
    appId: '1:887672134071:web:fb32cd8c0e8bc291bfb032',
    messagingSenderId: '887672134071',
    projectId: 'testing-84f41',
    authDomain: 'testing-84f41.firebaseapp.com',
    storageBucket: 'testing-84f41.appspot.com',
    measurementId: 'G-1KM2CWN8T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6SdAfe4nvkoKKYD_kGviKY81ihobt8nI',
    appId: '1:887672134071:android:2f8dd88580ded085bfb032',
    messagingSenderId: '887672134071',
    projectId: 'testing-84f41',
    storageBucket: 'testing-84f41.appspot.com',
  );
}
